package com.openlattice.chronicle.collection.upload

/**
 * `Context`-free seams the [UploadTelemetryCollectionModule] reads upload state through
 * (Phase 8, subphase 8A, refactor plan §11.1).
 *
 * The module never holds an Android `Context` (design §1C / refactor plan §6.1
 * guardrail 2). It reads queue depths, per-server upload state and WorkManager status
 * exclusively through these interfaces, which production wires from the application
 * `Context` once, in [UploadTelemetryModuleHolder], and then keeps only `Context`-free
 * handles. JVM unit tests supply fakes.
 *
 */

/**
 * Read-only snapshot of one upload server's **operational** state — the redaction-safe
 * projection of `UploadServerEntity` (refactor plan §11.1 steps 2–7, 16–18).
 *
 * This is deliberately **not** `UploadServerEntity`: `apiKey`, `participantId`,
 * `sourceDeviceId`, `studyId` and `url` are **never** copied into it. The module reads
 * upload telemetry — never a credential, a participant identifier, or a device secret
 * (design §1B.3, refactor plan §11.1 steps 16–18; guardrails 8A.1/8A.2).
 *
 * Every field here is operational diagnostics (`OPERATIONAL_DIAGNOSTICS`):
 *  - [serverId] is the autogenerated Room primary key (a `Long`), not a participant or
 *    study identifier;
 *  - [lastUploadError] / [lastSensorUploadError] are **not** copied verbatim — the module
 *    further redacts them (see [UploadTelemetryCollectionModule]); the raw last-error
 *    string is an exception message that could embed a host, body fragment or header, so
 *    diagnostics expose only a redacted token derived from it.
 *
 * @property serverId autogenerated `upload_servers.id` primary key.
 * @property enabled whether the server is currently enabled for upload.
 * @property consecutiveFailures consecutive usage-upload failure counter.
 * @property sensorConsecutiveFailures consecutive sensor-upload failure counter.
 * @property lastUsageUploadTime ISO-8601 timestamp string of the last usage upload, or
 *   `null`; an opaque timestamp, no participant data.
 * @property lastSensorUploadTime ISO-8601 timestamp string of the last sensor upload, or
 *   `null`.
 * @property hasUsageUploadError whether the server's last usage upload recorded an error.
 * @property hasSensorUploadError whether the server's last sensor upload recorded an error.
 */
public data class UploadServerTelemetry(
    val serverId: Long,
    val enabled: Boolean,
    val consecutiveFailures: Int,
    val sensorConsecutiveFailures: Int,
    val lastUsageUploadTime: String?,
    val lastSensorUploadTime: String?,
    val hasUsageUploadError: Boolean,
    val hasSensorUploadError: Boolean,
)

/**
 * Reads upload server state and queue depths for diagnostics — the only seam the
 * [UploadTelemetryCollectionModule] uses to reach Room.
 *
 * Production ([RoomUploadStateProbe]) projects each `UploadServerEntity` into a
 * [UploadServerTelemetry] **without ever copying `apiKey`**, reads `dataQueue` /
 * `sensor_samples` row counts, and counts `upload_stats` rows. All reads; no writes.
 */
public interface UploadStateProbe {

    /** Operational state of every upload server (enabled and disabled), credential-free. */
    public fun servers(): List<UploadServerTelemetry>

    /** Current `dataQueue` row count — the usage-events upload queue depth. */
    public fun usageQueueDepth(): Int

    /** Current `sensor_samples` row count — the sensor-samples upload queue depth. */
    public fun sensorQueueDepth(): Int

    /** Current `upload_stats` row count — number of per-(server, date) counter rows. */
    public fun uploadStatsRowCount(): Int
}

/**
 * WorkManager state of one combined-upload unique work chain (refactor plan §11.1
 * steps 9–12).
 *
 * WorkManager exposes `WorkInfo.State` and `runAttemptCount`; it does **not** expose a
 * next-fire wall-clock time, so the module never fabricates one (it lands in
 * `notTracked`). [constraintsMet] reflects whether all of the work's constraints (the
 * shared `NetworkType.CONNECTED` upload constraint) are currently satisfied.
 *
 * @property workName the unique work name (`combined_upload` or
 *   `combined_upload_immediate`).
 * @property state the latest `WorkInfo.State` name, or `null` when no work has ever been
 *   enqueued under [workName].
 * @property runAttemptCount the latest run-attempt count, or `0` when unknown — the same
 *   retry counter the worker itself branches on.
 * @property constraintsMet whether the work's constraints are currently met, or `null`
 *   when unknown / not exposed on this platform level.
 */
public data class CombinedUploadWorkStatus(
    val workName: String,
    val state: String?,
    val runAttemptCount: Int,
    val constraintsMet: Boolean?,
) {
    /** Whether WorkManager reports this work in a terminal failed/cancelled state. */
    public val isFailedOrCancelled: Boolean
        get() = state == "FAILED" || state == "CANCELLED"

    /** Whether WorkManager reports a retry is pending (`ENQUEUED` after a prior attempt). */
    public val isRetryPending: Boolean
        get() = state == "ENQUEUED" && runAttemptCount > 0
}

/**
 * Reads WorkManager state for the combined-upload unique work chains.
 *
 * Production ([WorkManagerUploadProbe]) wraps
 * `WorkManager.getInstance(ctx).getWorkInfosForUniqueWork(name)`. The module holds no
 * `Context`; the probe is constructed once, from the application `Context`, by
 * [UploadTelemetryModuleHolder].
 */
public interface UploadWorkProbe {

    /**
     * Status of the periodic combined-upload work (`combined_upload`), or `null` when no
     * such work has ever been enqueued or WorkManager is unreachable.
     */
    public fun periodicUploadStatus(): CombinedUploadWorkStatus?

    /**
     * Status of the one-time immediate combined-upload work
     * (`combined_upload_immediate`), or `null` when none has been enqueued.
     */
    public fun immediateUploadStatus(): CombinedUploadWorkStatus?
}
